version: '3'
services: 
  db:
    image: mysql:8.0
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
        - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
      - db_my.cnf:/etc/mysql/conf.d/my.conf
      - db_sql:/docker-entrypoint-initdb.d

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./app/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build: ./app/php
    volumes:
      - ./src:/var/www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - PMA_ARBITRARY=1 
      - PMA_HOST=db 
      - PMA_USER=admin 
      - PMA_PASSWORD=password
    links:
      - db
    ports: 
      - 8080:80
    volumes:
      - ./phpadmin/sessions:/sessions

volumes:
  db_data:
  db_my.cnf:
  db_sql:

